### ISSUE TITLE
Why use inotifywait on $RESOURCE_DIR ?

### ISSUE THREAD

**Issue by sylvainfaivre** [scambra/pve-migration-monitor#7]
Proxmox has the config files for all VMs and CTs in `/etc/pve/qemu-server` and `/etc/pve/lxc` so I don't understand why add `$RESOURCE_DIR` to the `inotifywait` line, in `/etc/pve-migration-monitor/migration-monitor` ?

Am I missing something here ?

During my testing, I had to remove `$RESOURCE_DIR` from that line, because it created lots of bugs, if often moved VM's IP to a host that doesn't have these VMs.

**Comment by scambra** [comment]
RESOURCE_DIR is the directory where failoverip scripts save failover IP used by vms, so when new IP is setup in a vm, file will be created in that directory and failoverip-up would add route

**Comment by sylvainfaivre** [comment]
OK I see, I didn't think about adding a new IP to an already running VM. Thanks !
